### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/statemint#70]
Final steps to deploy Statemine on Kusama:

- [ ] Ability to upgrade from Shell
  - [ ] Run on-genesis hooks on-runtime-upgrade
  - [ ] Migrate from default consensus to Aura
- [ ] Call filter https://github.com/paritytech/statemint/issues/64
- [ ] Final weights https://github.com/paritytech/statemint/pull/56

**Comment by JesseAbram** [comment]
as of final weights, kinda have to be last when the chain is locked in, once I get the ok, will take aprox 2 hours to get

**Comment by JesseAbram** [comment]
I already started a PR for statemine config, will need a couple more eyes on it before merge #71

**Comment by apopiak** [comment]
pulled out the shell upgrade stuff into a separate issue
